AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:vqfMKY/Bo3GYGDieYzwsa5M2RSnN6cKKVg==,iv:cmeHtpNxeEY9wlk5jcAgwIa/q/NGUY/rXL4T7GTGu6Q=,tag:8f+jNEw9En0QL4bO1J4Few==,type:str]
AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:5UJ4O6sSJRI7S+tJmdBHsddHv2L7B9DuMlzkRfMwqQ==,iv:Kodxf8rLwuY/gM0aztFzl7w+khI62rfEuYOwsY8sBhY=,tag:Hw9Rp22mQRaTgPTir7eLlQ==,type:str]
AWS_REGION: ENC[AES256_GCM,data:DMthGYTkWpFZbpBY0qo=,iv:3I69qDUUj7WvrGXDHlmBFN7sy5xjKb744poWsAxDMU0=,tag:szO65Ufl1LsVOZ2STAwTBQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUbGtrQ2RleEtycmhBdWJK
            eitIVzh1Uzl0SmJaMzdPdnh2dlRnQU8rc3o4CnlTMVl3bElLa2JXNzMzT2Nsb0l3
            cnVFNUdZNzZUNHFpOEpjdmE3ZHlGeEkKLS0tIDdXeFQrdjZHS1c4YWgrY2FscFhO
            a0swcjNaZmEzVTNLaGlqWnVlV2FFNkkKG6HyDFm7rwWhR6SKF8q5YibhaynROjGm
            kQn/f/i0nftASCz/aTEuBSPs3ZNMxtMZBB5u93WsMBMh6K5ChQ/1Vg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10rdeh7dwmtz2ka6urw4ufp566la0epu25yp2j0xk2zdrc9lg7g7qa0y4n6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmV2c1WlJmWCtWbWZTOUFC
            N3pWdUxaUk80NWErQzJVNzVDSDBhbmVqZkZZCkxhckdvWTVHTVVnT0lCcHVWSFVh
            RXBMbk5hS1pXWXJqZ2NNUVZ0eE1LajAKLS0tIGQyMUxOeU82L0RBOVc4UHd3OU9N
            dkxzdjB2a09na1dQb1VwQ3hLTnNWYjQKCuQzi5WpII6Acx/pRFD06And/yUwodqp
            Wybk2Z8w+ynICHC3E/+Zcm5zMgI4K4yWU/xUyjZNqQmatSwGAaMxcw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13f3kzht5m3awmqp54c2wgkd482z5m0f34z00lcklc3nsq7z383esea20py
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPTTBiUzdmY1J5bG96dld1
            aTl5TGl3WHNQOUhpc0xsRjBLSW9uSjZZWnhFCm9XMHNXSi9qK3dpV2x2dHFxemNZ
            MU5WVk5hTURCQ0RwaG1RbHp6WWZlTVUKLS0tIGNaeXZBbzhlbXNnWjlkRWVqbVp0
            dlNGMFNoQXJIOTl3U203QU9uWnpEejgKU1WVlTuGmMbTinjt+EpEE48kWnGVGck0
            wBPZqyTuj5wTMKThov/fY00lWRw8/yRIRaAfXSFRAMe17+XfviywzA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1whyxxr2zdn3gc8meu0jr4tugdcmw6xg8asxa00gqwx5yy3mfv9esw2p74a
    lastmodified: "2026-07-23T10:02:37Z"
    mac: ENC[AES256_GCM,data:7NGT1RlOyaDG7v7nPjMDELhLQsrhA4+WWsoYdIVMsOpQNAsF9uMkI4lGsX3EN7VTNyP/d8d9mWIySH8+MAFDSqo/St1esMoKJBngcXA882BJZIIGhZeWuzhBxidAHsEE6oXEf+ynaESsGjWMAYv11iU0J7zgZyoHhJgwPVNNu0U=,iv:db4hNJMeVg6eXBpYoQLd+ylDDR0tjc+gbnfIjLli6es=,tag:u0emN9rqdrYvQxjXGHsrYg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
